/*
The next code was generated by Repository Pattern Generator.
Be free to modify this file.

This extension was developed and designed by Francisco López Sánchez.
*/

using System;
using System.Collections.Generic;
using System.Linq.Expressions;

namespace Repository.Repository
{
    public interface IRepository<TEntity, TModel, TAdapter>
    {
        ICollection<TModel> Get();
        TModel Get(params object[] keys);
        ICollection<TModel> Get(Expression<Func<TEntity, bool>> where);
        TModel Add(TModel model);
        int Update(TModel model);
        int Delete(params object[] keys);
        int Delete(TModel model);
        int Delete(Expression<Func<TEntity, bool>> where);
    }
}