/*
The next code was generated by Repository Pattern Generator.
Be free to modify this file.

This extension was developed and designed by Francisco López Sánchez.
*/

using System.Collections.Generic;
using System.Linq;

namespace Repository.Adapter
{
    public abstract class Adapter<TEntity, TModel> : IAdapter<TEntity, TModel>
    {
        public abstract TEntity FromViewModel(TModel model);
        public abstract TModel FromModel(TEntity model);

        public ICollection<TEntity> FromViewModel(ICollection<TModel> model)
        {
            return model.Select(FromViewModel).ToList();
        }

        public ICollection<TModel> FromModel(ICollection<TEntity> model)
        {
            return model.Select(FromModel).ToList();
        }
    }
}