/*
The next code was generated by Repository Pattern Generator.
Be free to modify this file.

This extension was developed and designed by Francisco López Sánchez.
*/

using System.Collections.Generic;

namespace Repository.Adapter
{
    public interface IAdapter<TEntity, TModel>
    {
        TEntity FromViewModel(TModel model);
        TModel FromModel(TEntity model);
        ICollection<TEntity> FromViewModel(ICollection<TModel> model);
        ICollection<TModel> FromModel(ICollection<TEntity> model);
    }
}