/*
The next code was generated by Repository Pattern Generator.
Be free to modify this file.

This extension was developed and designed by Francisco López Sánchez.
*/

using System.Data.Entity;
using Repository.Adapter;
using Repository.Model;
using Repository.Repository;
using DataModel.ViewModel;

namespace ApiRedContactos.Repository
{
    public class MensajeRepository : EntityFrameworkRepository<Mensaje, MensajeModel, MensajeAdapter>
    {
        public MensajeRepository(DbContext context) : base(context) { }
    }
}
